### ISSUE TITLE
Budget Input Warehouse

### ISSUE THREAD

**Issue by AVHuntley** [afs1jes/Clarins-US-IR-Migration#38]

**Comment by mjaloia** [comment]
When switching from design to report view, tabs and grouping numbers disappear.  Any suggestions?

Otherwise, looks good.

**Comment by AVHuntley** [comment]
Those settings are controlled in the template properties menu:
**A3** > **Design** > **Template** > **Properties**
![image](https://user-images.githubusercontent.com/88676502/228363559-e69b6a2f-992f-419f-8752-9d3b96f1b331.png)

There, you can choose a bunch of different display options that will activate when in Report view. For now, I enabled 'Display Headings', 'Display Worksheet Tabs', 'Display Horizontal Scrollbar', and 'Display Vertical Scrollbar'. I think that should help.

![image](https://user-images.githubusercontent.com/88676502/228363950-6fc1460d-e819-4ce8-bcfa-aaeb5ef1cae7.png)

**Comment by mjaloia** [comment]
Terrific, thanks Alec.
